### ISSUE TITLE
Tokenizer does not include some tokens

### ISSUE THREAD

**Issue by tchayintr** [heytitle/Syllable-based-Neural-Thai-Word-Segmentation#9] opened 2021-08-10 16:27 UTC
### Context
Tokenizer does not include some tokens.

### Problem / Steps to reproduce
```
from ssg import syllable_tokenize
syllable_tokenize('เรียกว่าแรงดันแพร่ซึมซึ่งมีค่าเฉพาะ(เจอเมเนียมมีค่า0.3~0.4โวลต์ซิลิคอนมีค่า0.7~0.8โวลต์)')
['เรียก', 'ว่า',  'แรง',  'ดัน',  'แพร่',  'ซึม',  'ซึ่ง',  'มี',  'ค่า',  'เฉพาะ',  '(',  'เจอ',  'เม',  'เนียม',  'มี',  'ค่า',  '0.3~0.',  '4โวลต',  '์ซ',  'ิล',  'ิคอ',  'นม',  'ีค่',  'า0.7~0',  '.8โวล',  'ต์']
```

### Expected result:
The right bracket should be included in the result.
```
['เรียก', 'ว่า',  'แรง',  'ดัน',  'แพร่',  'ซึม',  'ซึ่ง',  'มี',  'ค่า',  'เฉพาะ',  '(',  'เจอ',  'เม',  'เนียม',  'มี',  'ค่า',  '0.3~0.',  '4โวลต',  '์ซ',  'ิล',  'ิคอ',  'นม',  'ีค่',  'า0.7\~0',  '.8โวล',  'ต์',  ')']
```

**Comment by p16i** [comment] 2021-08-13 07:28
Thank you for reporting! 

I think we should also file the issue at
- https://github.com/ponrawee/ssg (the main repository of SSG, cc: @ponrawee)
- https://github.com/PyThaiNLP/pythainlp (cc: @wannaphong)

**Comment by ponrawee** [comment] 2021-08-13 10:26
This seems to be a bug specific to `ssg`. I'll have a look. In the mean time, `syllable_tokenize` from PyThaiNLP seems to produce the correct results.

```
from pythainlp import syllable_tokenize
syllable_tokenize('เรียกว่าแรงดันแพร่ซึมซึ่งมีค่าเฉพาะ(เจอเมเนียมมีค่า0.3~0.4โวลต์ซิลิคอนมีค่า0.7~0.8โวลต์)')
```

produces

```
['เรียก', 'ว่า', 'แรง', 'ดัน', 'แพร่', 'ซึม', 'ซึ่ง', 'มี', 'ค่า', 'เฉพาะ', '(', 'เจอ', 'เม', 'เนียม', 'มี', 'ค่า', '0.3', '~', '0.4', 'โวลต์', 'ซิ', 'ลิ', 'คอน', 'มี', 'ค่า', '0.7', '~', '0.8', 'โวลต์', ')']
```

**Comment by ponrawee** [comment] 2021-08-13 12:19
@tchayintr 

I fixed this. Please update `ssg` to the latest version (0.08) and see if the issue is resolved.

The issue is due to the training data using `~` as a separator. I've employed a quickfix that simply treats `~` as any other character. The downside here is that `~` will never be seen as a syllable on its own (which probably should be the default behavior). This will be more properly fixed once I retrain ssg.

Thank you for the report.

**Closed as completed** 2021-08-13 13:10 UTC
